services:
  english_bot_redis:
    image: redis
    container_name: english_bot_redis
    hostname: english_bot_redis
    ports:
      - "6379:6379"
    entrypoint: ["redis-server"]
    networks:
      - english_network

  english_bot_mongo:
    image: mongo
    container_name: english_bot_mongo
    hostname: english_bot_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - english_network

  english_bot_postgres:
    image: postgres
    container_name: english_bot_postgres
    hostname: english_bot_postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - english_network

  english_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: english_bot
    depends_on:
      - english_bot_redis
      - english_bot_mongo
      - english_bot_postgres
    networks:
      - english_network

networks:
  english_network:
    driver: bridge

volumes:
  postgres_data:
  mongo_data: