version: '3.8'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - type: bind
        source: ./app/db/data/redis.conf
        target: /usr/local/etc/redis/redis.conf
      - type: volume
        source: redis
        target: /db/data/redis
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - app_network

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/db/data/mongo
    networks:
      - app_network

  python_app:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: python_app
    volumes:
      - ./app:/app
    depends_on:
      - redis
      - mongo
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongo:
  redis: